#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width		3
bspc config window_gap			8

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true

# colors
bspc config normal_border_color		      "#282a36"
bspc config active_border_color		      "#44475a"
bspc config focused_border_color	      "#bd93f9"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#ff5555"


bspc rule -a 'Chromium-browser' desktop="^2" state="tiled"
bspc rule -a 'discord' desktop="^3"
bspc rule -a 'TelegramDesktop' desktop="^4" state="tiled"
bspc rule -a 'Spotify' desktop="^5" follow=on
bspc rule -a dropdown sticky=on state=floating hidden=on

# Polybar
sh ~/.config/polybar/launch.sh &

# feh 
feh --bg-fill /home/triplek/Pictures/wallpapers/gentoo-drac.png &

# polkit 
exec /usr/libexec/polkit-gnome-authentication-agent-1 2> /dev/null &

# dunst
dunst &

# picom
picom --config /home/triplek/.config/picom.conf &

# cursor
xsetroot -cursor_name left_ptr
 
# st scratchpad autostart
st -c dropdown -e fish &
