#!/bin/bash

set $mod Mod4

font pango: Liberation Sans 10
title_align center

default_border pixel 4

set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer set Master 5%+ 
bindsym XF86AudioLowerVolume exec --no-startup-id amixer set Master 5%+ 
bindsym XF86AudioMute exec --no-startup-id amixer set Master toggle 

bindsym XF86AudioPlay exec playerctl play
bindsym XF86AudioPause exec playerctl pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous

bindsym XF86MonBrightnessDown exec brightnessctl set 2%-
bindsym XF86MonBrightnessUp exec brightnessctl set +2%

bindsym Print exec flameshot gui

bindsym $mod+space exec bemenu-run --fn 'Liberation Sans 12' --tb '#282a36' --tf '#bd93f9' --fb '#282a36' --ff '#8be9fd' --nb '#282a36' --nf '#f1fa8c' --hf '#50fa7b' --prompt nix-os

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec alacritty -e fish

# kill focused window
bindsym $mod+w kill


# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

#
# Moving around:
#
    # Move your focus around
    bindsym $mod+$left focus left
    bindsym $mod+$down focus down
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right
    # Move the focused window with the same, but add Shift
    bindsym $mod+Shift+$left move left
    bindsym $mod+Shift+$down move down
    bindsym $mod+Shift+$up move up
    bindsym $mod+Shift+$right move right


# split in horizontal orientation
bindsym $mod+Right split h

# split in vertical orientation
bindsym $mod+Down split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
# bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+s floating toggle

# scratchpad
bindsym $mod+Shift+grave move scratchpad
bindsym $mod+grave scratchpad show

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1:  "
set $ws2 "2:   "
set $ws3 "3:  "
set $ws4 "4:  "
set $ws5 "5:  "
set $ws6 "6:  "
set $ws7 "7:  "
set $ws8 "8:  "
set $ws9 "9:  "
set $ws10 "10:   "


# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+q exec pkill i3

# class                 border  backgr. text    indicator child_border
    client.focused          #bd93f9 #bd93f9 #282a36 #bd93f9   #bd93f9
    client.focused_inactive #282a36 #282a36 #bd93f9 #282a36   #282a36
    client.unfocused        #282a36 #282a36 #bd93f9 #282a36   #282a36
    client.urgent           #2f343a #900000 #ffffff #900000   #900000
    client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff

# Gaps
gaps inner 9
gaps outer 2

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        font pango: JetBrains Mono Nerd Font 11
	strip_workspace_numbers yes
        colors {
        background #282a36
        statusline #fefefe
        separator #ffffff
	#syntax              border    bg      fg
        focused_workspace   #bd93f9 #bd93f9 #282a36
        active_workspace    #333333 #282a36 #bd93f9
        inactive_workspace  #282a36 #222222 #bd93f9
        urgent_workspace    #282a36 #f1fa8c #282a36
        #binding_mode       #2f343a #900000 #ffffff
        }
        position top
        separator_symbol "|"
        status_command i3blocks -c /home/triplek/.config/i3blocks/i3blocks.conf 
        #i3bar_command i3bar --transparency
        
} 

# assign programs to WSs
for_window [class="Chromium-browser"] move to workspace $ws2
for_window [class="discord"] move to workspace $ws3
for_window [class="TelegramDesktop"] move to workspace $ws4
for_window [class="Spotify"] move to workspace $ws5
for_window [class="Subl"] move to workspace $ws7

# autostart
exec dunst
exec flameshot
exec feh --randomize --recursive --bg-fill /home/triplek/Pictures/wallpapers
bindsym $mod+Shift+n exec feh --randomize --recursive --bg-fill /home/triplek/Pictures/wallpapers
exec /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1 > /dev/null 2>&1
exec picom --config /home/triplek/.config/picom.conf

