#! /bin/bash

pkgs=$(apt list --installed 2> /dev/null | wc -l)
ram="$(free -h | awk '{print $3}' | sed -n '2p')"
TEMP="$(sensors|awk 'BEGIN{i=0;t=0;b=0}/id [0-9]/{b=$4};/Core/{++i;t+=$3}END{if(i>0){printf("%0.1f\n",t/i)}else{sub(/[^0-9.]/,"",b);print b}}')"
bat="$(acpi -b | awk '{print $4}')"
alsa="$(amixer get Master | sed -n '6p' | awk '{print $5}')"
BRIGHTNESS="$(xbacklight -get)"
date="$(date "+%d %B (%a) %l:%M%p")"

read cpu a b c previdle rest < /proc/stat
prevtotal="$((a+b+c+previdle))"
sleep 0.5
read cpu a b c idle rest < /proc/stat
total="$((a+b+c+idle))"
cpu="$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))"
icon0=""

R1="$(cat /sys/class/net/usb0/statistics/rx_bytes)"
T1="$(cat /sys/class/net/usb0/statistics/tx_bytes)"
sleep 1
R2="$(cat /sys/class/net/usb0/statistics/rx_bytes)"
T2="$(cat /sys/class/net/usb0/statistics/tx_bytes)"
TBPS="$(expr $T2 - $T1)"
RBPS="$(expr $R2 - $R1)"
TKBPS="$(expr $TBPS / 1024)"
RKBPS="$(expr $RBPS / 1024)"
icon=" "
icon1=" "

#while true; do
echo "  $pkgs    ${icon} ${RKBPS}kb ${icon1} ${TKBPS}kb     $ram   $icon0 $cpu %   ${TEMP} 糖    ${bat}    ${date} "
